app.url.db=172.24.111.23
app.username.db=postgres
app.password.db=password
app.port.db=5432
app.name.db=HCD
app.log.trace=C:/Users/CEKA/Desktop/DOCUMENT PERSO/2-DOCKER_FOLDER/1-DOCUMENT/3-LOG/HCD.log
app.port.start=8080