app.url.db=localhost
app.username.db=postgres
app.password.db=root
app.port.db=5432
app.name.db=HCD
app.log.trace= C:/Users/CEKA/Desktop/DOCUMENT PERSO/2-DOCKER_FOLDER/1-DOCUMENT/3-LOG/HCD.log
app.port.start=8086